name: Test and deploy the app

on:
  push:
    branches:
      - "production"
      - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ secrets.TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/slack-stockbots:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authorization with config file
        continue-on-error: true
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy the new image
        uses: actions-hub/kubectl@master
        with:
          args: apply -k ./deploy/base
